//
//  PdfInteractor.swift
//  OlympIt
//
//  Created Nariman on 10.05.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class PdfInteractor: PdfInteractorProtocol {
    weak var presenter: PdfPresenterProtocol?
}
