//
//  PdfProtocols.swift
//  OlympIt
//
//  Created Nariman on 10.05.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import Foundation

//MARK: Wireframe -
protocol PdfWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol PdfPresenterProtocol: AnyObject {
    func viewDidLoad()
    func getUrl() -> URL
}

//MARK: Interactor -
protocol PdfInteractorProtocol: AnyObject {
  var presenter: PdfPresenterProtocol?  { get set }
}

//MARK: View -
protocol PdfViewProtocol: AnyObject {
  var presenter: PdfPresenterProtocol?  { get set }
}
