//
//  PdfRouter.swift
//  OlympIt
//
//  Created Nariman on 10.05.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class PdfRouter: PdfWireframeProtocol {
    weak var viewController: UIViewController?
    
    static func createModule(pdfUrl: URL) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PdfViewController()
        let interactor = PdfInteractor()
        let router = PdfRouter()
        let presenter = PdfPresenter(interface: view, interactor: interactor, router: router, url: pdfUrl)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
