//
//  PdfViewController.swift
//  OlympIt
//
//  Created Nariman on 10.05.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit
import WebKit

final class PdfViewController: UIViewController, PdfViewProtocol {
	var presenter: PdfPresenterProtocol?

    private lazy var webView = OTWebView()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
    
    private func setup() {
        webView.uiDelegate = self
        webView.navigationDelegate = self
        webView.scrollView.showsVerticalScrollIndicator = false
        showLoadingAnimation()
        view.backgroundColor = .clear
        view.addSubview(webView)
        webView.snp.makeConstraints {
            $0.top.equalTo(self.view.safeAreaLayoutGuide.snp.top)
            $0.leading.trailing.bottom.equalToSuperview()
        }
        let request = URLRequest(url: presenter!.getUrl())
        webView.load(request)
    }
    
    private func setupWeb(url: String) {
        if let videoURL: URL = URL(string: url) {
            let request = URLRequest(url: videoURL)
            webView.load(request)
        }
    }
}

extension PdfViewController: WKNavigationDelegate, WKUIDelegate {
    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        hideLoadingAnimation()
        webView.isHidden = false
    }
}
