//
//  NewsListProtocols.swift
//  OlympIt
//
//  Created Nariman on 11.05.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import Foundation

//MARK: Wireframe -
protocol NewsListWireframeProtocol: AnyObject {
    func openNewsDetail(with model: NewsModel)
}
//MARK: Presenter -
protocol NewsListPresenterProtocol: AnyObject {
    func didGetNews(with news: NewsListModel)
    var news: NewsListModel { get set }
    func didSelectItemNews(at: Int)
}

//MARK: Interactor -
protocol NewsListInteractorProtocol: AnyObject {
  var presenter: NewsListPresenterProtocol?  { get set }
  func fetchNews()
}

//MARK: View -
protocol NewsListViewProtocol: AnyObject {
  var presenter: NewsListPresenterProtocol?  { get set }
  func reloadTable()
}
