//
//  NewsListInteractor.swift
//  OlympIt
//
//  Created Nariman on 11.05.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class NewsListInteractor: NewsListInteractorProtocol {
    weak var presenter: NewsListPresenterProtocol?
    private let repository: NewsRepository = NewsRepositoryImpl()

    func fetchNews() {
        repository.getNews { res in
            switch res {
            case .success(let success):
                self.presenter?.didGetNews(with: success)
            case .failure(let failure):
                print(failure)
            }
        }
    }
}
