//
//  NewsDetailProtocols.swift
//  OlympIt
//
//  Created Nariman on 11.05.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import Foundation

//MARK: Wireframe -
protocol NewsDetailWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol NewsDetailPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol NewsDetailInteractorProtocol: AnyObject {
  var presenter: NewsDetailPresenterProtocol?  { get set }
}

//MARK: View -
protocol NewsDetailViewProtocol: AnyObject {
  var presenter: NewsDetailPresenterProtocol?  { get set }
}
