//
//  NewsDetailPresenter.swift
//  OlympIt
//
//  Created Nariman on 11.05.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class NewsDetailPresenter: NewsDetailPresenterProtocol {
    weak private var view: NewsDetailViewProtocol?
    var interactor: NewsDetailInteractorProtocol?
    private let router: NewsDetailWireframeProtocol

    init(interface: NewsDetailViewProtocol, interactor: NewsDetailInteractorProtocol?, router: NewsDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}
